---
repos:
  # We'll activate these two later once we merged kdic-tutorials
  #- repo: https://github.com/psf/black-pre-commit-mirror
    # rev: 24.8.0
    # hooks:
      #- id: black-jupyter
        # language_version: python3
  #- repo: https://github.com/lyz-code/yamlfix/
    #rev: 1.17.0
    #hooks:
      #- id: yamlfix
        #language: python
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.2
    hooks:
      - id: check-github-workflows
        name: gh-workflows
        args: [--verbose]
      - id: check-github-actions
        name: gh-actions
        args: [--verbose]
  - repo: local
    hooks:
      - id: notebook-clean
        name: notebook-clean
        entry: jupyter nbconvert --ClearMetadataPreprocessor.enabled=True --inplace
          --log-level=ERROR
        language: python
        files: .*\.ipynb
