site_name: Khiops
site_url: https://khiops.org/

# Repository
repo_name: KhiopsML/Khiops
repo_url: https://github.com/KhiopsML/khiops

# Copyright
copyright: Copyright &copy; 2023-2025 Orange S.A.

theme:
  name: material
  logo: assets/images/Small_Logo_RGB.png
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: black
  favicon: assets/images/Small_Logo_RGB.png
  custom_dir: overrides
  font: false
  features:
    - navigation.tabs
    - navigation.path
    - navigation.tabs.sticky
    #- navigation.sections
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - content.tooltips

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - tables

extra:
  KHIOPS_VERSION: 10.2.4
  KHIOPS_PYTHON_VERSION: 10.2.4.0
  KHIOPS_SAMPLES_VERSION: 10.2.4
  KHIOPS_VIZ_VERSION: 11.0.9
  KHIOPS_COVIZ_VERSION: 11.1.2
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KhiopsML/khiops
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: G-JGJG6PJWFS
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://msurvey.orange.com/khiopsdoc" target="_blank" rel="noopener">feedback form</a>.

# Add extra Orange css
extra_css:
  - assets/stylesheets/orange-helvetica.min.css
  - assets/stylesheets/boosted.min.css
  - assets/stylesheets/orange.css
  - assets/stylesheets/main.css

# Add JS for Material plugins
extra_javascript:
  - assets/javascripts/mathjax.min.js
  - assets/javascripts/visu-menu.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - macros
  - search
  - mkdocs-jupyter:
      ignore_h1_titles: True
#  - blog
#  - privacy ## not usable with mathjax script

nav:
  - index.md
  - Installation:
      - setup/index.md
      - Packages:
          - conda: setup/conda.md
          - pip: setup/pip.md
          - docker notebook: setup/khiops-notebook.md
      - Standalone Applications:
          - Khiops Application: setup/nocode.md
          - Khiops Visualization: setup/visualization.md
          - Khiops Shared Library: setup/kni.md
  - How to:
      - Two APIs for different needs: tutorials/introduction.md
      - Scikit-learn API:
          - Quickstart Guide:  tutorials/quickstart.md
          - Single Table Classifier: tutorials/Notebooks/single_table_classifier.ipynb
          - No Need for Data Preparation: tutorials/Notebooks/No_data_Cleaning.ipynb
          - Interpretable Variable Encoding: tutorials/Notebooks/Optimal_Encoding.ipynb
          - Multi-Table Classifier: tutorials/Notebooks/multi_table_classifier.ipynb
          - "Auto Feature Engineering & More": tutorials/Notebooks/Use_in_any_ML_pipeline.ipynb
      - Core API & Dictionaries:
          - Start Using Dictionaries: tutorials/kdic_intro.md
          - Single Table Classifier: tutorials/Notebooks/single_table_classifier_core.ipynb
          - Single-Table Learning: tutorials/kdic_single_table.md
          - Multi-Table Learning: tutorials/kdic_multi_table.md
          - Multi-Table Classifier: tutorials/Notebooks/multi_table_classifier_core.ipynb
      - Production ready:
          - Easy Deployment: tutorials/---.md
          - Cloud Storages: tutorials/storage.md
          - Khiops on Kubernetes: tutorials/k8s.md
  - Foundations:
      - What Makes Khiops Different: learn/understand.md
      - An Original Formalism: learn/modl.md
      - Optimal Encoding: learn/preprocessing.md
      - Auto Feature Engineering: learn/autofeature_engineering.md
      - Parsimonious Training: learn/learning_models.md
      - Auto Hardware Adaptation: learn/hardware_adaptation.md
      - Bibliography: references.md
  - API Reference:
      - Python API Docs: api-docs/python-api.md
      - Dictionary Rules:
          - Basic:
            - Numerical Comparisons: api-docs/kdic/numerical-comparisons.md
            - Categorical Comparisons: api-docs/kdic/categorical-comparisons.md
            - Logical Operators: api-docs/kdic/logical-operators.md
            - Data Copy and Conversion: api-docs/kdic/data-copy-and-conversion.md
            - String Rules: api-docs/kdic/string-rules.md
            - Math Rules: api-docs/kdic/math-rules.md
            - Date Rules: api-docs/kdic/date-rules.md
            - Time Rules: api-docs/kdic/time-rules.md
            - Timestamp Rules: api-docs/kdic/timestamp-rules.md
            - TimestampTZ Rules: api-docs/kdic/timestamp-tz-rules.md
          - Multi-Table:
            - Introduction: api-docs/kdic/multi-table-rules-introduction.md
            - Entity Rules: api-docs/kdic/entity-rules.md
            - Table Rules: api-docs/kdic/table-rules.md
            - Table Management Rules: api-docs/kdic/table-management-rules.md
          - Technical Structures & Rules:
            - Introduction: api-docs/kdic/structures-introduction.md
            - Vector Rules: api-docs/kdic/vector-rules.md
            - Hash Map Rules: api-docs/kdic/hash-map-rules.md
            - Data Preparation Rules: api-docs/kdic/data-preparation-rules.md
            - Recoding Rules: api-docs/kdic/recoding-rules.md
            - Predictor Rules: api-docs/kdic/predictor-rules.md
            - Coclustering Rules: api-docs/kdic/coclustering-rules.md
  - Discussions: https://github.com/orgs/KhiopsML/discussions
  - Contact Us: contact.md
#    - Blog:
#      - blog/index.md
