---
name: Build Khiops Documentation
description: Action to build the Khiops documentation web site
inputs:
  khiops-version:
    description: Version of Khiops core
    required: true
  khiops-python-version:
    description: Version of the Khiops Python library
    required: true
  khiops-doc-ref:
    description: Revision of the Khiops documentation web site
    default: ''
  khiops-samples-version:
    description: Version of the Khiops samples
    required: true
  khiops-viz-version:
    description: Version of the Khiops visualization tool
    required: true
  khiops-coviz-version:
    description: Version of the Khiops covisualization tool
    required: true
  khiops-gcs-driver-version:
    description: Version of the Khiops GCS driver
    required: true
  khiops-s3-driver-version:
    description: Version of the Khiops S3 driver
    required: true
  add-versions-to-the-menu:
    description: Add the versions.md to the menu
    default: 'true'
runs:
  using: composite
  steps:
    - name: Checkout doc sources
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.khiops-doc-ref }}
        # Fetch all branches and tags
        fetch-depth: 0
        fetch-tags: true
        # Keep versions.md
        clean: false
    - name: Install requirements
      shell: bash
      run: pip install -r requirements.txt
    - name: Add versions to the menu
      if: inputs.add-versions-to-the-menu == 'true'
      shell: bash
      run: |
        # Copy the versions file to the docs folder
        cp versions.md docs/
        # Add the versions file to the menu
        echo -e "\n  - ${{ inputs.khiops-version }}: versions.md" >> mkdocs.yml
    - name: Fetch Khiops Python API docs
      shell: bash
      run: |
        # Fetch the API docs
        wget -O khiops_api_docs.zip "https://github.com/KhiopsML/khiops-python/releases/download/${{ inputs.khiops-python-version }}/khiops-api-docs-${{ inputs.khiops-python-version }}.zip"

        # Put Python API docs into the site source dir, as it is *untraced by
        # Git*, hence it will get built *and* deployed (see
        # https://www.mkdocs.org/user-guide/deploying-your-docs/)
        # After build, the Python API docs are in the
        # site/api-docs/python-api/api folder.
        mkdir -p docs/api-docs/python-api/api

        # Unzip the API doc into the docs/python-api/api/ folder, while
        # stripping the doc/_build/html sub-directories and excluding the
        # doc/_build/html/_downloads subdirectory
        bsdtar --strip-components=3 --exclude '_downloads/' -C docs/api-docs/python-api/api -xvf khiops_api_docs.zip

        # Remove the Khiops Python API ZIP archive
        rm -f khiops_api_docs.zip
    - name: Install Khiops-Related Requirements to Run the Tutorials
      shell: bash
      env:
        KHIOPS_VERSION: ${{ inputs.khiops-version }}
        KHIOPS_PYTHON_VERSION: ${{ inputs.khiops-python-version }}
        KHIOPS_SAMPLES_VERSION: ${{ inputs.khiops-samples-version }}
      run: |
        # Install Khiops Core
        sudo apt-get install lsb-release unzip -y
        CODENAME=$(lsb_release -cs)
        wget -O khiops_core.deb "https://github.com/KhiopsML/khiops/releases/download/${KHIOPS_VERSION}/khiops-core-openmpi_${KHIOPS_VERSION}-1-${CODENAME}.amd64.deb"
        sudo dpkg -i khiops_core.deb || sudo apt-get -f -y install
        rm -f khiops_core.deb
        # Install Khiops Python
        KHIOPS_PYTHON_PACKAGE_VERSION=$(echo "$KHIOPS_PYTHON_VERSION" | tr -d '-' | sed -r 's/(.*)\.([^.]*)/\1\2/')
        pip install "https://github.com/KhiopsML/khiops-python/releases/download/${KHIOPS_PYTHON_VERSION}/khiops-${KHIOPS_PYTHON_PACKAGE_VERSION}.tar.gz"
        # Download samples
        wget -O khiops_samples.zip "https://github.com/KhiopsML/khiops-samples/releases/download/${KHIOPS_SAMPLES_VERSION}/khiops-samples-${KHIOPS_SAMPLES_VERSION}.zip"
        mkdir -p ./khiops_samples && unzip khiops_samples.zip -d ./khiops_samples
        rm -f khiops_samples.zip
        # Install plotting tools, used in the tutorials
        pip install matplotlib seaborn pycaret
    - name: Build site
      shell: bash
      env:
        KHIOPS_VERSION: ${{ inputs.khiops-version }}
        KHIOPS_PYTHON_VERSION: ${{ inputs.khiops-python-version }}
        KHIOPS_SAMPLES_VERSION: ${{ inputs.khiops-samples-version }}
        KHIOPS_VIZ_VERSION: ${{ inputs.khiops-viz-version }}
        KHIOPS_COVIZ_VERSION: ${{ inputs.khiops-coviz-version }}
        KHIOPS_GCS_DRIVER_VERSION: ${{ inputs.khiops-gcs-driver-version }}
        KHIOPS_S3_DRIVER_VERSION: ${{ inputs.khiops-s3-driver-version }}
        KHIOPS_SAMPLES_DIR: ./khiops_samples
      run: |
        # Build the site pages into the site/ directory
        mkdocs build --strict --verbose
        # Hide the logo from the Python files
        find site/api-docs/python-api/api -name "*.html" -print0 | xargs -0 sed -i 's/div class="sidebar-logo-container"/div class="sidebar-logo-container" style="visibility: hidden; max-height: 0"/g'
    - name: Clean the Git doc repo state
      shell: bash
      run: |
        # Remove source Python API docs
        rm -fr docs/api-docs/python-api/api
        # Remove added markdown file
        rm -f docs/versions.md
        # Checkout the mkdocs file so that the Git repo state is clean
        git checkout mkdocs.yml
        # Remove the samples directory
        rm -fr ./khiops_samples
    # The following step is needed to ensure that the post-action steps take the
    # same versions of the build-doc action into account
    - name: Checkout doc sources to the current repository reference
      uses: actions/checkout@v4
      with:
        # Keep versions.md
        clean: false
