---
name: Check Links
on:
  pull_request:
    branches:
      - main
      - dev
jobs:
  check-links:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
      - name: Install documentation requirements
        run: uv sync --frozen --extra notebooks
      - name: Retrieve the version number of Khiops Visualization Desktop from the latest release on GitHub
        if: env.KHIOPS_VIZ_VERSION == ''
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # "gh release view" shows the latest release in the project, we extract its version (without the leading "v")
          LAST_TAG="$(gh --repo https://github.com/KhiopsML/khiops-visualization-desktop/ release view --json tagName --jq '.tagName')"
          echo "KHIOPS_VIZ_VERSION=${LAST_TAG#v}" >> "$GITHUB_ENV"
      - name: Convert tutorial notebooks
        env:
          EXECUTE_KHIOPS_TUTORIALS: "false"
        run: uv run python scripts/convert_notebooks.py
      - name: Build site
        env:
          KHIOPS_VERSION: ${{ env.KHIOPS_VERSION }}
          KHIOPS_PYTHON_VERSION: ${{ env.KHIOPS_PYTHON_VERSION }}
          KHIOPS_SAMPLES_VERSION: ${{ env.KHIOPS_SAMPLES_VERSION }}
          KHIOPS_VIZ_VERSION: ${{ env.KHIOPS_VIZ_VERSION }}
          KHIOPS_GCS_DRIVER_VERSION: ${{ env.KHIOPS_GCS_DRIVER_VERSION }}
          KHIOPS_S3_DRIVER_VERSION: ${{ env.KHIOPS_S3_DRIVER_VERSION }}
          EXECUTE_KHIOPS_TUTORIALS: "false"
        run: uv run zensical build --strict
      - name: Install required system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libarchive-tools
      - name: Fetch Khiops Python API docs
        run: |
          wget -O khiops_api_docs.zip "https://github.com/KhiopsML/khiops-python/releases/download/${{ env.KHIOPS_PYTHON_VERSION }}/khiops-api-docs-${{ env.KHIOPS_PYTHON_VERSION }}.zip"
          mkdir -p site/api-docs/python-api/api
          bsdtar --strip-components=3 -C site/api-docs/python-api/api -xvf khiops_api_docs.zip
          rm -f khiops_api_docs.zip
      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-
      - name: Check for broken links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --root-dir site --cache --no-progress --accept 200,403 --exclude 'file:///.*\d+\.\d+\.\d+' --exclude 'https://khiops\.org' 'site/**/*.html'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

