---
name: Website
on:
  workflow_dispatch:
    inputs:
      deploy-gh-pages:
        description: Deploy to GH Pages
        required: true
        type: boolean
        default: false
permissions:
  contents: write
jobs:
  build-or-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install required system dependencies
        run: sudo apt-get install wget libarchive-tools
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Set up the version information in the environment
        run: cat environment.env | grep -vE "^(#|$)" >> "$GITHUB_ENV"
      - name: Prepare the versions markdown file
        run: |
          echo "# Current version: [${{ env.KHIOPS_VERSION }}][current_version]" >> versions.md
          echo "# Other versions:" >> versions.md
          echo "  - [${{ env.KHIOPS_OTHER_VERSION }}][other_version]" >> versions.md
          echo "[current_version]: /" >> ./versions.md
          echo "[other_version]: /${{ env.KHIOPS_OTHER_VERSION }}/" >> versions.md
      - name: Build other version site
        uses: ./.github/actions/build-doc
        with:
          khiops-doc-ref: ${{ env.KHIOPS_DOC_OTHER_REF }}
          khiops-version: ${{ env.KHIOPS_OTHER_VERSION }}
          khiops-python-version: ${{ env.KHIOPS_PYTHON_OTHER_VERSION }}
          khiops-samples-version: ${{ env.KHIOPS_SAMPLES_OTHER_VERSION }}
          khiops-viz-version: ${{ env.KHIOPS_VIZ_OTHER_VERSION }}
          khiops-coviz-version: ${{ env.KHIOPS_COVIZ_OTHER_VERSION }}
          khiops-gcs-driver-version: ${{ env.KHIOPS_GCS_DRIVER_OTHER_VERSION }}
          khiops-s3-driver-version: ${{ env.KHIOPS_S3_DRIVER_OTHER_VERSION }}
      - name: Move other version site to dedicated folder
        run: mv site ${{ env.KHIOPS_OTHER_VERSION }}
      - name: Build current version site
        uses: ./.github/actions/build-doc
        with:
          # khiops-doc-ref is '', that is, the current branch ref
          khiops-version: ${{ env.KHIOPS_VERSION }}
          khiops-python-version: ${{ env.KHIOPS_PYTHON_VERSION }}
          khiops-samples-version: ${{ env.KHIOPS-SAMPLES_VERSION }}
          khiops-viz-version: ${{ env.KHIOPS_VIZ_VERSION }}
          khiops-coviz-version: ${{ env.KHIOPS_COVIZ_VERSION }}
          khiops-gcs-driver-version: ${{ env.KHIOPS_GCS_DRIVER_VERSION }}
          khiops-s3-driver-version: ${{ env.KHIOPS_S3_DRIVER_VERSION }}
      - name: Move other version site inside the main site
        run: mv ${{ env.KHIOPS_OTHER_VERSION }} site/
      - name: Upload the site docs as an artifact (PR)
        if: github.event_name == 'pull_request' || inputs.deploy-gh-pages == false
        uses: actions/upload-artifact@v4
        with:
          name: khiops-doc
          path: ./site/
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Deploy site to GH pages (Manual)
        if: github.event_name == 'workflow_dispatch' && inputs.deploy-gh-pages == true
        run: mkdocs gh-deploy --strict --force
