---
name: Website
on:
  workflow_dispatch:
    inputs:
      execute-khiops-tutorials:
        description: Execute khiops-doc's own tutorial notebooks
        required: true
        type: boolean
        default: false
      deploy-gh-pages:
        description: Deploy to GH Pages
        required: true
        type: boolean
        default: false
      check-links:
        description: Check for broken links
        required: true
        type: boolean
        default: false
permissions:
  contents: write
jobs:
  build-or-deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Install required system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install wget libarchive-tools
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.11
      - name: Checkout doc sources
        uses: actions/checkout@v6
      - name: Set up the version information in the environment
        run: cat environment.env | grep -vE "^(#|$)" >> "$GITHUB_ENV"
      - name: Retrieve the version number of Khiops Visualization Desktop from the latest release on GitHub
        if: env.KHIOPS_VIZ_VERSION == ''
        id: khiops-viz-version
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # "gh release view" shows the latest release in the project, we extract its version (without the leading "v")
          LAST_TAG="$(gh --repo https://github.com/KhiopsML/khiops-visualization-desktop/ release view --json tagName --jq '.tagName')"
          echo "value=${LAST_TAG#v}" >> "$GITHUB_OUTPUT"
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
      - name: Install Khiops core
        run: |
          # Create virtual environment
          uv venv
      - name: Build documentation
        run: |
          # Activate virtual environment
          . .venv/bin/activate

          # Build the documentation
          ARGS=(
            --khiops-version "${{ env.KHIOPS_VERSION }}"
            --khiops-python-version "${{ env.KHIOPS_PYTHON_VERSION }}"
            --khiops-python-ref "${{ env.KHIOPS_PYTHON_REF }}"
            --khiops-samples-version "${{ env.KHIOPS_SAMPLES_VERSION }}"
            --khiops-python-tutorial-ref "${{ env.KHIOPS_PYTHON_TUTORIAL_VERSION }}"
            --khiops-viz-version "${{ env.KHIOPS_VIZ_VERSION || steps.khiops-viz-version.outputs.value }}"
            --khiops-gcs-driver-version "${{ env.KHIOPS_GCS_DRIVER_VERSION }}"
            --khiops-s3-driver-version "${{ env.KHIOPS_S3_DRIVER_VERSION }}"
            --khiops-azure-driver-version "${{ env.KHIOPS_AZURE_DRIVER_VERSION }}"
          )
          if [[ "${{ inputs.execute-khiops-tutorials }}" == "true" ]]; then
            ARGS+=(--execute-tutorials)
          fi
          bash .github/scripts/build-doc.sh "${ARGS[@]}"
      - name: Check for broken links
        if: inputs.check-links
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --no-progress
            --root-dir ./site
            --accept 200,403
            --exclude 'file:///.*\d+\.\d+\.\d+'
            --remap 'https://khiops.org/ file://${{ github.workspace }}/site/'
            'site/**/*.html'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload the site docs as an artifact (PR)
        if: inputs.deploy-gh-pages == false
        uses: actions/upload-artifact@v7
        with:
          name: khiops-doc
          path: ./site/
      - name: Configure Git Credentials
        if: github.event_name == 'workflow_dispatch' && inputs.deploy-gh-pages == true
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Deploy site to GH pages (Manual)
        if: github.event_name == 'workflow_dispatch' && inputs.deploy-gh-pages == true
        run: |
          # Push built site directory contents to GH pages
          uv run ghp-import -m "Deployed ${GITHUB_SHA:0:7}" --push --force --no-jekyll ./site/
